apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-webservice-deployment
spec:
  selector:
    matchLabels:
      app: employee-webservice
  replicas: 3
  template:
    metadata:
      labels:
        app: employee-webservice
    spec:
      containers:
        - name: employee-webservice-container
          image: bharath210/employee-ws:34
          ports:
            - containerPort: 7500
          env:   # Setting Enviornmental Variables
            - name: DB_HOST  
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: host

            - name: DB_NAME  
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: dbName

            - name: DB_USERNAME  
              value: root

            - name: DB_PASSWORD 
              value: root
