apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management-system-deployment
spec:
  selector:
    matchLabels:
      app: employee-management-system
  replicas: 3
  template:
    metadata:
      labels:
        app: employee-management-system
    spec:
      containers:
        - name: employee-management-system-container
          image: bharath210/employee-management-system:latest
          ports:
            - containerPort: 7500
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   
              value: mysql

            - name: DB_NAME  
              value: hdfc

            - name: DB_USERNAME  
              value: root

            - name: DB_PASSWORD 
              value: root

apiVersion: v1 # Kubernetes API version
kind: Service 
metadata: 
  name: employee-management-system-service
spec:
  selector:
    app: employee-management-system
  ports:
    - protocol: "TCP"
      port: 7500 # The port that the service is running on in the cluster
      targetPort: 7500 # The port exposed by the service
  type: LoadBalancer # type of the service.
