apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management-system-deployment
spec:
  selector:
    matchLabels:
      app: employee-management-system
  replicas: 3
  template:
    metadata:
      labels:
        app: employee-management-system
    spec:
      containers:
        - name: employee-management-system-container
          image: bharath210/employee-management-system:latest
          ports:
            - containerPort: 7500
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql

            - name: DB_NAME  # Setting Database name from configMap
              value: hdfc

            - name: DB_USERNAME  # Setting Database username from Secret
              value: root

            - name: DB_PASSWORD # Setting Database password from Secret
              value: root

