
apiVersion: v1 
kind: Service 
metadata: 
  name: employee-webservice-service
spec:
  selector:
    app: employee-webservice
  ports:
    - protocol: "TCP"
      port: 7500 
      targetPort: 7500 
  type: LoadBalancer 